const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const FILTER_ALL = 'FILTER_ALL';
const FILTER_ACTIVE = 'FILTER_ACTIVE';
const FILTER_COMPLETED = 'FILTER_COMPLETED';

export default {
  ADD_TODO,
  REMOVE_TODO,
  TOGGLE_TODO,
  FILTER_ALL,
  FILTER_ACTIVE,
  FILTER_COMPLETED
};
