const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const NEW_TEXT = 'NEW_TEXT';
const UPDATE_TODO = 'UPDATE_TODO';
const FILTER_ALL = 'FILTER_ALL';
const FILTER_ACTIVE = 'FILTER_ACTIVE';
const FILTER_COMPLETED = 'FILTER_COMPLETED';
const SET_FILTER = 'SET_FILTER';
const MODAL_ERROR = 'MODAL_ERROR';
const MODAL_STATUS = 'MODAL_STATUS';
const MODAL_REMOVE = 'MODAL_REMOVE';
const HIDE_MODALS = 'HIDE_MODALS';
const SET_PARAMS = 'SET_PARAMS';
const RESET_TEXT = 'RESET_TEXT';

export default {
  ADD_TODO,
  REMOVE_TODO,
  NEW_TEXT,
  UPDATE_TODO,
  FILTER_ALL,
  FILTER_ACTIVE,
  FILTER_COMPLETED,
  SET_FILTER,
  MODAL_ERROR,
  MODAL_STATUS,
  HIDE_MODALS,
  MODAL_REMOVE,
  SET_PARAMS,
  RESET_TEXT
};
