const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const NEW_TEXT = 'NEW_TEXT';
const UPDATE_TODO = 'UPDATE_TODO';

export default {
  ADD_TODO,
  REMOVE_TODO,
  NEW_TEXT,
  UPDATE_TODO
};
